
// This file has been generated by the GUI designer. Do not modify.
namespace GFreeRDP
{
	public partial class ConnectionDialog
	{
		private global::Gtk.HBox hboxHostname;
		private global::Gtk.Label labelHostname;
		private global::Gtk.Entry entryHostname;
		private global::Gtk.HBox hboxCredentials;
		private global::Gtk.Label labelUsername;
		private global::Gtk.Entry entryUsername;
		private global::Gtk.Label labelPassword;
		private global::Gtk.Entry entryPassword;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonConnect;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GFreeRDP.ConnectionDialog
			this.Name = "GFreeRDP.ConnectionDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Connection");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child GFreeRDP.ConnectionDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "connectionDialog_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child connectionDialog_VBox.Gtk.Box+BoxChild
			this.hboxHostname = new global::Gtk.HBox ();
			this.hboxHostname.Name = "hboxHostname";
			this.hboxHostname.Spacing = 6;
			// Container child hboxHostname.Gtk.Box+BoxChild
			this.labelHostname = new global::Gtk.Label ();
			this.labelHostname.Name = "labelHostname";
			this.labelHostname.LabelProp = global::Mono.Unix.Catalog.GetString ("Hostname:");
			this.hboxHostname.Add (this.labelHostname);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hboxHostname [this.labelHostname]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hboxHostname.Gtk.Box+BoxChild
			this.entryHostname = new global::Gtk.Entry ();
			this.entryHostname.CanFocus = true;
			this.entryHostname.Name = "entryHostname";
			this.entryHostname.IsEditable = true;
			this.entryHostname.InvisibleChar = '•';
			this.hboxHostname.Add (this.entryHostname);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hboxHostname [this.entryHostname]));
			w3.Position = 1;
			w1.Add (this.hboxHostname);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.hboxHostname]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child connectionDialog_VBox.Gtk.Box+BoxChild
			this.hboxCredentials = new global::Gtk.HBox ();
			this.hboxCredentials.Name = "hboxCredentials";
			this.hboxCredentials.Spacing = 6;
			// Container child hboxCredentials.Gtk.Box+BoxChild
			this.labelUsername = new global::Gtk.Label ();
			this.labelUsername.Name = "labelUsername";
			this.labelUsername.LabelProp = global::Mono.Unix.Catalog.GetString ("Username:");
			this.hboxCredentials.Add (this.labelUsername);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hboxCredentials [this.labelUsername]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hboxCredentials.Gtk.Box+BoxChild
			this.entryUsername = new global::Gtk.Entry ();
			this.entryUsername.CanFocus = true;
			this.entryUsername.Name = "entryUsername";
			this.entryUsername.IsEditable = true;
			this.entryUsername.InvisibleChar = '•';
			this.hboxCredentials.Add (this.entryUsername);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hboxCredentials [this.entryUsername]));
			w6.Position = 1;
			// Container child hboxCredentials.Gtk.Box+BoxChild
			this.labelPassword = new global::Gtk.Label ();
			this.labelPassword.Name = "labelPassword";
			this.labelPassword.LabelProp = global::Mono.Unix.Catalog.GetString ("Password:");
			this.hboxCredentials.Add (this.labelPassword);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hboxCredentials [this.labelPassword]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hboxCredentials.Gtk.Box+BoxChild
			this.entryPassword = new global::Gtk.Entry ();
			this.entryPassword.CanFocus = true;
			this.entryPassword.Name = "entryPassword";
			this.entryPassword.IsEditable = true;
			this.entryPassword.InvisibleChar = '•';
			this.hboxCredentials.Add (this.entryPassword);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hboxCredentials [this.entryPassword]));
			w8.Position = 3;
			w1.Add (this.hboxCredentials);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(w1 [this.hboxCredentials]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Internal child GFreeRDP.ConnectionDialog.ActionArea
			global::Gtk.HButtonBox w10 = this.ActionArea;
			w10.Name = "connectionDialog_ActionArea";
			w10.Spacing = 10;
			w10.BorderWidth = ((uint)(5));
			w10.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child connectionDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w10 [this.buttonCancel]));
			w11.Expand = false;
			w11.Fill = false;
			// Container child connectionDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonConnect = new global::Gtk.Button ();
			this.buttonConnect.CanDefault = true;
			this.buttonConnect.CanFocus = true;
			this.buttonConnect.Name = "buttonConnect";
			this.buttonConnect.UseUnderline = true;
			this.buttonConnect.Label = global::Mono.Unix.Catalog.GetString ("Connect");
			this.AddActionWidget (this.buttonConnect, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w10 [this.buttonConnect]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 516;
			this.DefaultHeight = 135;
			this.Show ();
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.buttonConnect.Clicked += new global::System.EventHandler (this.OnButtonConnectClicked);
		}
	}
}
