
// This file has been generated by the GUI designer. Do not modify.
namespace GFreeRDP
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action FileAction;
		private global::Gtk.Action HelpAction;
		private global::Gtk.Action ConnectAction;
		private global::Gtk.Action QuitAction;
		private global::Gtk.VBox vboxMain;
		private global::Gtk.MenuBar menuBarMain;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GFreeRDP.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.HelpAction, null);
			this.ConnectAction = new global::Gtk.Action ("ConnectAction", global::Mono.Unix.Catalog.GetString ("Connect"), null, null);
			this.ConnectAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Connect");
			w1.Add (this.ConnectAction, null);
			this.QuitAction = new global::Gtk.Action ("QuitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, null);
			this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
			w1.Add (this.QuitAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "GFreeRDP.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child GFreeRDP.MainWindow.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox ();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menuBarMain'><menu name='FileAction' action='FileAction'><menuitem name='ConnectAction' action='ConnectAction'/><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='HelpAction' action='HelpAction'/></menubar></ui>");
			this.menuBarMain = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menuBarMain")));
			this.menuBarMain.Name = "menuBarMain";
			this.vboxMain.Add (this.menuBarMain);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.menuBarMain]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			this.Add (this.vboxMain);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 409;
			this.DefaultHeight = 300;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.ConnectAction.Activated += new global::System.EventHandler (this.OnConnectActionActivated);
		}
	}
}
